development:
  adapter: postgresql
  encoding: unicode
  database: bedepravedtest
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: bedepraveddev
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: bedepravedprod
  pool: 5
  password: